notifications:
  email:
    - sebastien@malot.fr

language: php

php:
  - 5.3
  - 5.4
#  - 5.5

env:
  - PATH=$PATH:/home/travis/.composer/vendor/bin
  - DRUPAL_HOSTNAME="http://localhost"
  - DRUPAL_LOGIN=admin
  - DRUPAL_PASSWORD=admin

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # Install Apache.
  - sudo apt-get install apache2 libapache2-mod-fastcgi php5-xdebug php5-cli

  # Enable php-fpm.
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Configure Apache virtual hosts.
  - sudo cp -f travis/apache_virtual_hosts.txt /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)/../drupal?g" --in-place /etc/apache2/sites-available/default

  # Make sure all Apache configuration takes effect.
  - sudo service apache2 restart
  - curl -v "http://localhost"

  # Download Drush.
  - composer global require drush/drush:dev-master --prefer-source
  - cd /home/travis/.composer/vendor/drush/drush
  - drush version

  # Download Drupal core.
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --branch 7.x --depth 1 http://git.drupal.org/project/drupal.git
  - cd $TRAVIS_BUILD_DIR/../drupal

  # Add Coveralls.io integration.
#  - cd $TRAVIS_BUILD_DIR/../drupal
#  - composer require satooshi/php-coveralls:0.6.* --prefer-source

  # Copy Currency into Drupal core.
#  - cp -Rv $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../drupal/modules/

  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`

before_script:
  # Install Drupal core.
  - cd $TRAVIS_BUILD_DIR/../drupal
  - drush -v site-install standard --db-url=mysql://root:@localhost/drupal --yes --account-pass=admin
  # Adding Services modules.
  - drush -v en -y services rest_server xmlrpc_server services_oauth
  # Adding Drupal Commerce modules.
  - drush -v en -y commerce commerce_product commerce_cart commerce_order commerce_tax commerce_payment commerce_services
  - drush -v sql-query --file=$TRAVIS_BUILD_DIR/travis/script_services.sql

script:
  # Run PHPUnit tests and submit code coverage statistics.
#  - cd $TRAVIS_BUILD_DIR/../drupal/core
#  - mkdir -p build/logs
#  - vendor/bin/phpunit -c ../modules/currency/phpunit.xml.dist --bootstrap tests/bootstrap.php --verbose --debug --coverage-clover build/logs/clover.xml || exit 1
#  - php vendor/bin/coveralls -v -c ../modules/currency/.coveralls.yml

  - ./vendor/bin/atoum -d src/Smalot/Drupal/Services/Tests/ -ncc

#  - phpenv rehash
#
#  # Enable Simpletest and run Simpletest tests.
#  - drush en --yes simpletest
#  - drush cr
#  - cd $TRAVIS_BUILD_DIR/../drupal
#  - php core/scripts/run-tests.sh --verbose --color --concurrency 4 --php `which php` --url http://localhost "Currency" "Currency Intl" | tee /tmp/test.txt
#  # Simpletest does not exit with code 0 on success, so we will need to analyze
#  # the output to ascertain whether the tests passed.
#  - TEST_EXIT=${PIPESTATUS[0]}
#  - TEST_SIMPLETEST=$(! egrep -i "([0-9]+ fails)|(PHP Fatal error)|([0-9]+ exceptions)" /tmp/test.txt > /dev/null)$?
#  - if [ $TEST_EXIT -eq 0 ] && [ $TEST_SIMPLETEST -eq 0 ]; then exit 0; else exit 1; fi
